version: '3'
services:
  run_migration:
    build: .
    command: rails db:migrate RAILS_ENV=development
    volumes:
      - .:/url_shortener
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/url_shortener
    ports:
      - "3000:3000"
    depends_on:
      - run_migration