default: &default
  adapter: postgresql
  encoding: unicode
  username: url_short
  password: url_short!23
  host: 172.17.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: url_shortener_api_development
  port: 5431

test:
  <<: *default
  database: url_shortener_api_test
  port: 5430

production:
  <<: *default
  database: url_shortener_api_production
  username: url_shortener_api
  password: <%= ENV['URL_SHORTENER_API_DATABASE_PASSWORD'] %>
